language: node_js
node_js:
  - 12
services:
  - mongodb
install:
  - npm install -g serverless
  - npm install
script:
  - npm test
deploy:
  provider: script
  script: sls deploy
  on:
    branch: master